<a href="https://colab.research.google.com/github/sairam7/python_projects/blob/master/XGBoost_Classifier_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install xgboost


In [0]:
from sklearn import datasets
import xgboost as xgb

iris = datasets.load_iris()
X = iris.data
y = iris.target

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

In [0]:
D_train = xgb.DMatrix(X_train, label=Y_train)
D_test = xgb.DMatrix(X_test, label=Y_test)

In [0]:
param = {
    'eta': 0.3, 
    'max_depth': 3,  
    'objective': 'multi:softprob',  
    'num_class': 3} 

steps = 20  # The number of training iterations

In [0]:
model = xgb.train(param, D_train, steps)

In [7]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, accuracy_score

preds = model.predict(D_test)
best_preds = np.asarray([np.argmax(line) for line in preds])

print("Precision = {}".format(precision_score(Y_test, best_preds, average='macro')))
print("Recall = {}".format(recall_score(Y_test, best_preds, average='macro')))
print("Accuracy = {}".format(accuracy_score(Y_test, best_preds)))

Precision = 0.9743589743589745
Recall = 0.9523809523809524
Accuracy = 0.9666666666666667


In [9]:
print(preds[0])

[0.00773756 0.01917275 0.97308964]


In [10]:
print(np.argmax(preds[0]))

2


In [11]:
print(best_preds)

[2 0 1 2 0 2 1 1 0 2 2 0 2 1 0 1 0 2 2 1 0 0 0 2 0 2 2 2 2 0]


In [16]:
print(X_train[0],Y_train[0])

[6.2 2.2 4.5 1.5] 1


In [15]:
print(D_train)

In [0]:
model.dump_model('dump.raw.txt')

In [18]:
!ls


dump.raw.txt  sample_data


In [20]:
!cat dump.raw.txt

booster[0]:
0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=0.425454557
	2:leaf=-0.218918934
booster[1]:
0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=-0.212727293
	2:[f3<1.75] yes=3,no=4,missing=3
		3:[f2<4.94999981] yes=5,no=6,missing=5
			5:leaf=0.4118644
			6:leaf=-0.0620689802
		4:[f2<4.85000038] yes=7,no=8,missing=7
			7:leaf=-7.66345476e-09
			8:leaf=-0.209774464
booster[2]:
0:[f2<4.75] yes=1,no=2,missing=1
	1:[f3<1.54999995] yes=3,no=4,missing=3
		3:leaf=-0.218446627
		4:leaf=-7.66345476e-09
	2:[f3<1.75] yes=5,no=6,missing=5
		5:[f2<4.94999981] yes=7,no=8,missing=7
			7:leaf=-0.128571451
			8:leaf=0.217241377
		6:[f2<4.85000038] yes=9,no=10,missing=9
			9:leaf=0.128571421
			10:leaf=0.419548899
booster[3]:
0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=0.292988449
	2:leaf=-0.195771977
booster[4]:
0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=-0.189252526
	2:[f3<1.75] yes=3,no=4,missing=3
		3:[f2<5.05000019] yes=5,no=6,missing=5
			5:leaf=0.277911276
			6:leaf=-0.123482101
		4: